version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Secret-Cat
    ports:
      - "1433:1433"
    cap_add:
      - SYS_PTRACE
    # volumes:
    #   - ./data:/var/opt/mssql/data
    #   - ./log:/var/opt/mssql/log
    #   - ./secrets:/var/opt/mssql/secrets


  # subscriber:
  #   container_name: subscriber
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Subscriber/Dockerfile
  #   depends_on:
  #     - rabbitmq

  # catalogue:
  #   container_name: catalogue-service
  #   build:
  #     context: .
  #     dockerfile: Catalogue/Dockerfile
  #   ports:
  #     - "5001:80"
  #   depends_on:
  #     - rabbitmq


  # ordering:
  #   container_name: ordering-service
  #   build:
  #     context: .
  #     dockerfile: Ordering/Dockerfile
  #   ports:
  #     - "5002:80"
  #   depends_on:
  #     - rabbitmq



networks:
  default:
    driver: bridge
