###
GET http://localhost:5259/event


###
GET http://localhost:5259/user


###
GET http://localhost:5259/products

###
POST http://localhost:5259/products
Content-Type: application/json

{
    "title":"Patates",
    "stock" : {
        "amount":100.0,
        "unitType" : 0
    },
    "prices": [
        {
            "currencyType":0,
            "amount": 22.5
        }
    ]
}


###
GET http://localhost:5109/event



###
GET http://localhost:5001/event

###
GET http://localhost:5002/event